// THIS FILE IS AUTO-GENERATED by vite-plugin-asset-sizes.mjs.
// Run `npm run build` to update. Do not edit manually.
//
// Assets counted (bytes, uncompressed):
//   board.json                                            4654 B  (Phaser preload)
//   board.png                                             4249 B  (Phaser preload)
//   chaossounds.json                                      3835 B  (Phaser preload)
//   classicunits.json                                   195908 B  (Phaser preload)
//   classicunits.png                                     32187 B  (Phaser preload)
//   cursors.json                                         16156 B  (Phaser preload)
//   cursors.png                                           2507 B  (Phaser preload)
//   effects.json                                         20889 B  (Phaser preload)
//   effects.png                                            758 B  (Phaser preload)
//   hats.png                                              5101 B  (Phaser preload)
//   magic-armour.png                                      2702 B  (Phaser preload)
//   rain.json                                              910 B  (Phaser preload)
//   rain.png                                               969 B  (Phaser preload)
//   unit-glow.png                                          115 B  (Phaser preload)
//   wizards.png                                           1370 B  (Phaser preload)
//   chaossounds.ogg                                     147151 B  (audio (preferred format))
//   classicunits.css                                     32364 B  (lazy CSS bundle)
//   debug.css                                            16450 B  (lazy CSS bundle)
//   Game.css                                             24849 B  (lazy CSS bundle)
//   LoadingScreen.css                                     3806 B  (lazy CSS bundle)
//   style.css                                            61408 B  (lazy CSS bundle)
//   classicunits.js                                     201463 B  (lazy JS bundle)
//   debug.js                                             57107 B  (lazy JS bundle)
//   Game.js                                             141042 B  (lazy JS bundle)
//   LoadingScreen.js                                      8910 B  (lazy JS bundle)
//   main.js                                               2541 B  (lazy JS bundle)
//   phaser.js                                          1352563 B  (lazy JS bundle)
//   style.js                                               698 B  (lazy JS bundle)
//   window.js                                            15065 B  (lazy JS bundle)
//   _plugin-vue_export-helper.js                         70854 B  (lazy JS bundle)
//   TOTAL                                              2428581 B

/** Total uncompressed bytes fetched by the browser after the loading screen appears. */
export const TOTAL_GAME_ASSET_BYTES = 2428581;
