// THIS FILE IS AUTO-GENERATED by vite-plugin-asset-sizes.mjs.
// Run `npm run build` to update. Do not edit manually.
//
// Assets counted (bytes, uncompressed):
//   board.json                                            4654 B  (Phaser preload)
//   board.png                                             2158 B  (Phaser preload)
//   chaossounds.json                                      3835 B  (Phaser preload)
//   classicunits.json                                   189887 B  (Phaser preload)
//   classicunits.png                                     32187 B  (Phaser preload)
//   cursors.json                                         16156 B  (Phaser preload)
//   cursors.png                                           2507 B  (Phaser preload)
//   effects.json                                         20889 B  (Phaser preload)
//   effects.png                                            758 B  (Phaser preload)
//   hats.png                                              5101 B  (Phaser preload)
//   magic-armour.png                                      2702 B  (Phaser preload)
//   pointer-arrow.png                                     1018 B  (Phaser preload)
//   rexcolorreplacepipelineplugin.min.js                  7834 B  (Phaser preload)
//   rexperlinplugin.min.js                               10068 B  (Phaser preload)
//   unit-glow.png                                          115 B  (Phaser preload)
//   wizards.png                                           1370 B  (Phaser preload)
//   chaossounds.ogg                                     147151 B  (audio (preferred format))
//   Game.css                                             20235 B  (lazy CSS bundle)
//   LoadingScreen.css                                     1223 B  (lazy CSS bundle)
//   Game.js                                             299324 B  (lazy JS bundle)
//   LoadingScreen.js                                     70474 B  (lazy JS bundle)
//   phaser.js                                          1198735 B  (lazy JS bundle)
//   window.js                                            14825 B  (lazy JS bundle)
//   TOTAL                                              2053206 B

/** Total uncompressed bytes fetched by the browser after the loading screen appears. */
export const TOTAL_GAME_ASSET_BYTES = 2053206;
