export enum UnitStatus {
    Engulfs = "engulf",
    Expires = "expires",
    ExpiresGivesSpell = "expiresGivesSpell",
    Flying = "flying",
    Invulnerable = "invuln",
    Mount = "mount",
    MountAny = "mountAny",
    Spreads = "spread",
    Structure = "struct",
    Transparent = "trans",
    Tree = "tree",
    Undead = "undead",
    Wizard = "wizard",
    NoCorpse = "noCorpse",
    AttackUndead = "attackUndead",
    // Wizard-specific buffs
    ShadowForm = "shadowForm",
    MagicWings = "magicWings",
    MagicShield = "magicShield",
    MagicArmour = "magicArmour",
    MagicSword = "magicSword",
    MagicBow = "magicBow",
    MagicKnife = "magicKnife",
}
