export enum UnitStatus {
    Engulfs = "engulf",
    Expires = "expires",
    ExpiresGivesSpell = "expiresGivesSpell",
    Flying = "flying",
    Invulnerable = "invuln",
    Mount = "mount",
    Spreads = "spread",
    Structure = "struct",
    Transparent = "trans",
    Tree = "tree",
    Undead = "undead",
    Wizard = "wizard",
    NoCorpse = "noCorpse",
}
